# Generated by Django 3.2 on 2023-08-11 18:54

import api_yamdb.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Укажите логин', max_length=150, unique=True, validators=[api_yamdb.validators.validate_username], verbose_name='Логин'),
        ),
    ]
